### ISSUE TITLE
Attaching to Chrome when already started

### ISSUE THREAD

**Issue by BobbyCannon-Quantros** [BobbyCannon/TestR#6]
I’ve faced with one more issue. I added debug parameters to the Chrome’s shortcut and started browser. After that run the test and get the following exception:

Result StackTrace:   
at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
   at TestR.Application.WaitForComplete(Int32 minimumDelay)
   at TestR.Web.Browser.WaitForComplete(Int32 minimumDelay)
   at TestR.Web.Browser.Refresh()
   at TestR.Web.Browsers.Chrome.Create(Boolean bringToFront)
   at POConTestR.AutomationTests.UnitTest1.TestMethod1() in D:\Quantros\Source\Repos\Quantros.QEUtils\POConTestR.AutomationTests\UnitTest1.cs:line 20
Result Message:      
Test method POConTestR.AutomationTests.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: Cannot process request because the process (208) has exited.

**Comment by vaha** [comment]
Issue is reproducible only for the Create() method (Attach() and AttachOrCreate() work fine).

Some additional info: Win 8.1, Chrome 58.0.3029.110 (64-bit), TestR 1.0.24
